### ISSUE TITLE
When using a hardware keyboard (with a tablet for example), the software keyboard continue to pop up with every keystroke 

### ISSUE THREAD

**Issue by clubtech** [BlueBubblesApp/bluebubbles-app#2030] opened 2022-04-27 21:24 UTC
When using the Bluebubbles app with a hardware keyboard connected (for example, using a tablet or Samsung DeX), the software keyboard pops up with every letter keystroke which makes it impossible to type a message.

This is also happening when using Bluebubbles with Microsoft's YourPhone app and a Samsung phone as it emulates a hardware keyboard.

This issue is only happening with Bluebubbles. All other applications I use work fine with the hardware keyboard.

**Comment by zlshames** [comment] 2022-05-09 20:04
This might just be an underlying Flutter issue. Not sure why it would be happening, but I assume upgrading flutter (when they've fixed it) will fix the issue. Leaving this open until then

**Comment by clubtech** [comment] 2022-05-14 16:38
Thank you for looking into this. Maybe this is resolved in Flutter 3 that was just announced?

**Comment by zlshames** [comment] 2022-05-15 14:26
> Thank you for looking into this. Maybe this is resolved in Flutter 3 that was just announced?

We've just built the engine/framework for flutter 3 and are currently testing builds with it. Stay tuned!

**Comment by tneotia** [comment] 2022-05-27 16:49
On the flutter 3 builds I was unable to reproduce on tab s7+ with keyboard case

**Comment by tneotia** [comment] 2022-06-02 10:30
I can actually reproduce this now ...

**Comment by zlshames** [comment] 2022-06-02 13:23
Since you've reproduced it (easily?), I'm putting this for 1.9.0

**Comment by zlshames** [comment] 2022-06-03 22:09
We believe we've fixed this. Closing. This will be in v1.9.0

**Closed by zlshames** 2022-06-03 22:09 UTC

**Comment by clubtech** [comment] 2022-11-13 18:25
I would like to ask if this can be reopened as there are still issues with this.
Trying to use the app on a Samsung Galaxy Tab s8 with a hardware keyboard attached and DeX mode enabled the software keyboard pops up on every single keystroke. This also happens sometimes when using the app in normal tablet mode with hardware keyboard attached.
