### ISSUE TITLE
Linux app spellchecker

### ISSUE THREAD

**Issue by jjowitt** [BlueBubblesApp/bluebubbles-app#2721] opened 2024-04-16 16:48 UTC
Please implement a spellchecker for the Linux app.

**Comment by jjoelj** [comment] 2024-04-16 16:52
Duplicate of https://github.com/BlueBubblesApp/bluebubbles-app/issues/1994.

This feature was added in the latest Linux Beta version and will be brought to the stable release when I have time.
You can install the beta version from the FlatHub Beta repo or use the tarball under [this release](https://github.com/BlueBubblesApp/bluebubbles-app/releases/tag/v1.13.0%2B63)

**Closed by jjoelj** 2024-04-16 16:52 UTC

**Comment by jjowitt** [comment] 2024-04-16 21:01
Hi - I just installed the beta but do not see the spellcheck working. Is
there a setting to enable it?


Thanks,

James Jowitt

Staff Consultant *|* Public Sector Professional Services

*Splunk >     |     *540.424.2745 *|     ***@***.***

*Schedule a Meeting with me*: https://calendly.com/jjowitt
*Washington D.C. **|* Cupertino *|* London *|* Hong Kong *|* San Francisco
| Seattle *|* Plano *|* Singapore *|* Munich

**Comment by jjowitt** [comment] 2024-04-16 21:21
Nevermind its working, its just slow to pop up with the red underlines.


Thanks,

James Jowitt

Staff Consultant *|* Public Sector Professional Services

*Splunk >     |     *540.424.2745 *|     ***@***.***

*Schedule a Meeting with me*: https://calendly.com/jjowitt
*Washington D.C. **|* Cupertino *|* London *|* Hong Kong *|* San Francisco
| Seattle *|* Plano *|* Singapore *|* Munich
