### ISSUE TITLE
Android FindMy Pins not updating on map even though location is

### ISSUE THREAD

**Issue by jaysqvl** [BlueBubblesApp/bluebubbles-app#2701] opened 2024-03-14 01:51 UTC
MacOS Ventura 13.6.4 Private API active
Pixel 8 Pro

Essentially, as stated in the title, the device locations are updated but the map pins don't move. I've tried hitting the refresh button to no avail on the app as well as reinstalling, reopening, etc. All other private api features appear to work fine as well.

What's odd is that it works as intended on the Windows 11 desktop app. The pins properly reflect their location on the map.

FindMy on my personal apple devices work fine. It also works fine on the patched VM (the addresses are in the right place but obviously the patched VM can't display the map due to no VM GPU passthrough).

**Comment by tneotia** [comment] 2024-04-21 16:39
dupe of #2703

**Closed by tneotia** 2024-04-21 16:39 UTC
