### ISSUE TITLE
[Material] tapping on any message should show its delivery/read receipt and then tapping again should hide it (except for the most recent)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1150] opened 2021-07-22 04:26 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@jojejo` in `#feedback`.

**Comment by tneotia** [comment] 2021-09-29 19:43
dupe of recent ticket

**Closed by tneotia** 2021-09-29 19:43 UTC
Labels: Enhancement, UX, Bot Created, Difficulty: Medium
