### ISSUE TITLE
Feature request: Emoji button on Windows/Linux clients

### ISSUE THREAD

**Issue by cole-bauml** [BlueBubblesApp/bluebubbles-app#2741] opened 2024-05-05 12:32 UTC
Emojis have already been coded into the app, it isn't unreasonable to add a button for emojis.

You can send them by typing :EMOJINAME:, but nobody remembers all of those. Please add a button to search for emojis.

Thanks!

**Comment by jjoelj** [comment] 2024-05-05 15:54
Duplicate of #2585

**Closed** 2024-05-05 15:54 UTC
