### ISSUE TITLE
Game pigeon attachment causes sync freeze

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1216] opened 2021-07-29 20:05 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#general`.

**Comment by zlshames** [comment] 2021-08-02 20:57
Marking as hard due to it being difficult to replicate from what we've seen. This _may_ have also been caused by Ngrok's session limit, and we may just have thought it was Game Pidgeon. Technically those messages shouldn’t be handled any different

**Comment by CSab6482** [comment] 2021-08-02 21:01
In [this release](https://github.com/iandwelker/smserver/releases/tag/v0.6.3) of SMServer, @iandwelker noted that one of the changes was `Added support for GamePidgeon & Podcast Rich Links`. At first, I thought this meant SMServer had added the ability to interact with GamePigeon, but Janshai explained to me
> It does not add support for interacting with GamePigeon games. I seriously doubt that this will ever be possible, but if I ever figure out how to do it, I’ll definitely push an update with support for it. 
>
>However, past GamePigeon messages (the ones that, for example, show a battleship picture with the message “you lost!” Or “your turn”) were crashing SMServer before version 0.6.3. The app was trying to parse them as website rich links (which was obviously incorrect), which threw some errors and crashed the app. So I fixed some things up so that it now parses them correctly as GamePigeon messages and gets the necessary information to display them correctly in the web interface. However, as I said before, you still cannot interact with them; they’re simply static images with a caption. 
>
>I also noticed that it was trying to parse podcast links as regular website links, which, while not technically incorrect, was causing it to retrieve some incorrect information for the podcasts. I just added some specific rules for how to parse podcasts into the app and now it shows the correct information about podcasts on the rich links in the web interface.

I'm not sure if this is at all related, but seeing as I just remembered this, I figured I'd leave all this information in a comment.

**Comment by tneotia** [comment] 2022-11-22 06:28
Completed in full rewrite

**Closed by tneotia** 2022-11-22 06:28 UTC
Labels: Bug, Bot Created, Difficulty: Hard
