### ISSUE TITLE
Server connection setup page's "Sign in with Google" results in "Microsoft Edge can't read and write to its data directory" (WebView)

### ISSUE THREAD

**Issue by Tekkie1** [BlueBubblesApp/bluebubbles-app#2628] opened 2023-12-28 06:23 UTC
When trying to connect to the server on the Windows desktop app, selecting "Sign in with Google" opens a new window (Edge WebView2) and displays the following error:

![image](https://github.com/BlueBubblesApp/bluebubbles-app/assets/88729801/60dab37f-a1d1-49d1-a1e6-44da733d86da)

Manual configuration is required to move forward with setup.

Opening this ticket at the request of Joel via Discord.

**Comment by jdkruzr** [comment] 2024-02-05 00:28
I'm having this exact same problem.

**Comment by Hasbro35** [comment] 2024-02-22 17:33
Also seeing this error.  Note I didn't see it with the Microsoft App, but I was trying to install using the executable to see if that would allow auto-startup, since that wasn't working for me with the Microsoft app.

**Comment by tneotia** [comment] 2024-04-21 16:46
dupe of #2640

**Closed by tneotia** 2024-04-21 16:46 UTC
