### ISSUE TITLE
Cannot Open Android App

### ISSUE THREAD

**Issue by nep2ner** [BlueBubblesApp/bluebubbles-app#2845] opened 2024-11-09 13:17 UTC
After updating the Android app via Obtainium, the app opened and I toggled the background service notifications off then back on, went in & out of one chat (but didn't perform any actions there), then I got a notification that BlueBubbles kept crashing. Now, BlueBubbles will not open even if I force kill it and/or clear the cache. 

```
type: crash
osVersion: google/bluejay/bluejay:15/AP3A.241105.007/2024110700:user/release-keys
package: com.bluebubbles.messaging:20002069, targetSdk 34
process: com.bluebubbles.messaging
processUptime: 502 + 722 ms
installer: dev.imranr.obtainium

java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern : %s%
	at java.net.URLDecoder.decode(URLDecoder.java:214)
	at java.net.URLDecoder.decode(URLDecoder.java:143)
	at io.socket.global.Global.decodeURIComponent(Global.java:28)
	at io.socket.parseqs.ParseQS.decode(ParseQS.java:29)
	at io.socket.engineio.client.Socket.<init>(Socket.java:195)
	at io.socket.engineio.client.Socket.<init>(Socket.java:169)
	at io.socket.client.Manager$Engine.<init>(Manager.java:555)
	at io.socket.client.Manager$1.run(Manager.java:233)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.client.Manager.open(Manager.java:222)
	at io.socket.client.Manager.open(Manager.java:212)
	at io.socket.client.Socket$3.run(Socket.java:126)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by zlshames** [comment] 2024-11-09 14:04
This is a known (& fixed, internally) bug and is caused by a % in your password. Update will be released soon. Apologies!

**Closed as completed** 2024-11-13 19:35 UTC
Labels: Fixed Internally
