### ISSUE TITLE
[Desktop] Add option to not minimize to tray

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1683] opened 2021-11-11 18:27 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@jojejo` in `#desktop-development`.

**Comment by jjoelj** [comment] 2021-11-12 05:14
duplicate of #1649

**Closed by jjoelj** 2021-11-12 05:14 UTC
Labels: Bot Created
