### ISSUE TITLE
[Tablet Mode] text field does not refocus after sending a message

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#1923] opened 2022-03-12 08:18 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#feedback`.

**Comment by zlshames** [comment] 2022-03-19 15:15
I think this is a duplicate of #1943

**Closed by zlshames** 2022-03-19 15:15 UTC
Labels: Bot Created
