### ISSUE TITLE
Inline message replies in native notification?

### ISSUE THREAD

**Issue by nattofriends** [BlueBubblesApp/bluebubbles-app#2523] opened 2023-07-19 05:33 UTC
Thanks for developing BlueBubbles. It works great on Windows desktop.

I notice that quite a few native notification actions are supported. Would it also be possible to add support for [inline reply fields in native notifications](https://web.dev/push-notifications-display-a-notification/#actions-inline-replies)?

**Comment by tneotia** [comment] 2023-08-19 19:56
dupe of #1875

**Closed by tneotia** 2023-08-19 19:56 UTC
