### ISSUE TITLE
Black bar at top of Android app

### ISSUE THREAD

**Issue by SpaceSaver** [BlueBubblesApp/bluebubbles-app#2587] opened 2023-11-30 01:54 UTC
There is a large black horizontal bar at the top of the app when the Android app is installed on a Chromebook.  It appears that the app is not stretching to fill all of the way to the top.  The bar is constant no matter how the window is resized and limits the viewport, which is annoying to look at.

**Comment by tneotia** [comment] 2023-12-01 03:23
dupe of #2502

**Closed by tneotia** 2023-12-01 03:23 UTC
