### ISSUE TITLE
First message sent to a brand new chat will disappear

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-app#1599] opened 2021-09-25 22:12 UTC

**Comment by tneotia** [comment] 2021-11-05 18:06
cannot reproduce on big sur so @zlshames can you look into this one?

**Comment by zlshames** [comment] 2022-11-22 13:42
This will probably be addressed by the rewrite

**Comment by tneotia** [comment] 2022-11-29 13:23
Resolved in rewrite

**Closed by tneotia** 2022-11-29 13:23 UTC
Labels: Bug, priority: high, UX
