### ISSUE TITLE
Findmy not updating address or location of friends 

### ISSUE THREAD

**Issue by littleflo** [BlueBubblesApp/bluebubbles-app#2674] opened 2024-02-15 15:09 UTC
I am running the latest server version on MacOS Monterey with the latest Android app version(beta).  I can see my friends last location and address, but it won't update.

![Screenshot_20240215_090306_BlueBubbles.jpg](https://github.com/BlueBubblesApp/bluebubbles-app/assets/77301082/07ad97f1-652b-4783-a3fa-256a49f3deaf)

![Screenshot_20240215_090333_BlueBubbles.jpg](https://github.com/BlueBubblesApp/bluebubbles-app/assets/77301082/4f5d197b-e15d-435f-be57-872400f0b2de)

**Comment by zlshames** [comment] 2024-02-15 19:46
Can you double check your Mac to see if their location is updated in their Messages chat? Using the chat details popup icon

**Comment by littleflo** [comment] 2024-02-15 20:38
> Can you double check your Mac to see if their location is updated in their Messages chat? Using the chat details popup icon

On my end it shows their current location.

**Comment by zlshames** [comment] 2024-02-15 20:54
> > Can you double check your Mac to see if their location is updated in their Messages chat? Using the chat details popup icon
> 
> On my end it shows their current location.

Hmmm, after you use the refresh button in the android app, do you see logs on the server saying that locations have been updated? The way it works is you ask FindMy to refresh the locations, and as the updated locations come in, they should be updated in the app. But whether they come in depends on the private API. 

Are you on Sonoma?

**Comment by tneotia** [comment] 2024-04-21 16:41
dupe of #2703

**Closed by tneotia** 2024-04-21 16:41 UTC
