### ISSUE TITLE
Google sign in doesn't work on windows

### ISSUE THREAD

**Issue by Electronik21** [BlueBubblesApp/bluebubbles-app#2549] opened 2023-09-08 13:45 UTC
When you try to sign in with google on first setup, it just opens a blank window and doesn't do anything. Once you close the window, it shows a message saying "Something went wrong authenticating with Google! Exception: No access token!"

**Comment by Electronik21** [comment] 2023-09-08 17:55
Another thing- a few seconds after the error message appears the app crashes and closes itself. Nothing in the logs except for the same error message

**Comment by SpaceSaver** [comment] 2023-12-07 22:49
Had same issue on Linux

**Comment by whatthefilament** [comment] 2023-12-19 15:33
I've found that it does this when using the package downloaded direct from Github but not when using package downloaded from the windows app store. Maybe you have firewall rule or network rule that's blocking network access from apps from unknown sources.

**Comment by war59312** [comment] 2024-01-19 21:18
I get the same behavior from the Microsoft Store version as well, sadly.

And looks like indeed, it's the Windows firewall, turn it off, and then google login works as expected.

**Comment by bobbyl140** [comment] 2024-01-31 21:16
I have the same issue, it happens in both the GitHub build and the UWP app from Microsoft. I don't personally wish to use Google sign-in but I wanted to test something with it and the issue happened.

**Comment by weflower** [comment] 2024-02-18 20:01
Try changing the folder permissions on the installation directory. Had the same issue and opened a doc bug here:
https://github.com/BlueBubblesApp/bluebubbles-app/issues/2640

ideally it would be fixed in the app itself though.

**Comment by tneotia** [comment] 2024-04-21 16:46
dupe of #2640

**Closed by tneotia** 2024-04-21 16:46 UTC

**Comment by JtMotoX** [comment] 2025-06-04 07:38
I also ran into this issue if I install it through the Github release page.

Opening the Security settings for the "BlueBubbles" directory and grant the "Users" group "Full control" fixes it for me. Thanks @weflower
