### ISSUE TITLE
Sent messages disappear (sometimes)

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#752] opened 2021-02-06 05:40 UTC
I'm not sure how I'd be able to replicate this to test it, but the photo was still visible from the details menu. Exiting the chat and restarting the app did not make the photo reappear in the chat history

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#nightly-bugs`.

**Comment by zlshames** [comment] 2021-06-16 12:44
Can you provide more information on this? If not, I'm tempted to close it until it comes up again. For instance, do you have a video or screenshot so I can easily reproduce it?

**Comment by CSab6482** [comment] 2021-09-10 17:10
Idk how I missed the comment, but I've gotten messages that disappear into the void before (as recently as yesterday), and they usually repopulate when exiting and and re-entering the chat

**Comment by zlshames** [comment] 2021-09-10 18:49
> Idk how I missed the comment, but I've gotten messages that disappear into the void before (as recently as yesterday), and they usually repopulate when exiting and and re-entering the chat

Yep, known issue. Not sure the fix just yet

**Comment by zlshames** [comment] 2021-09-10 18:51
Marking this as Medium/Hard because the diagnosis/reproduction is the hardest part. This happens when starting a brand new chat, as well as other random times. No rhyme or reason. The messages appear when leaving and re-entering the chat. This leads me to believe the NewMessageManager listener within MessagesView is kinda off on the logic

**Comment by tneotia** [comment] 2021-11-05 22:34
This has not happened since 0.3.0 server, marking as closed for now.

**Closed by tneotia** 2021-11-05 22:34 UTC
Labels: Bug, UX, Bot Created, Difficulty: Hard, Difficulty: Medium
