### ISSUE TITLE
Chats can't be started using images

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-app#679] opened 2021-01-17 19:57 UTC
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by CSab6482** [comment] 2021-01-20 17:43
This seems to be a duplicate of issue #668

**Comment by zlshames** [comment] 2021-06-16 21:58
@CSab6482 any idea if this is still an issue?

**Comment by CSab6482** [comment] 2021-06-16 22:02
Yes and I think it's one that can only be solved with private API usage as @sgtaziz has previously told me that it is a limitation from Apple's part. I'll test this today in BB as well as in the other apps.

**Comment by CSab6482** [comment] 2021-06-16 23:48
I was unable to create a new chat with an image in BlueBubbles, below is a screenshot of how it looked on my phone as well as in the Terminal on my Mac.
![Screenshot_20210616-184208](https://user-images.githubusercontent.com/53708281/122308598-afa5c080-ceda-11eb-9d37-d0bea3ed4c11.jpg)
![Screen Shot 2021-06-16 at 6 41 51 PM](https://user-images.githubusercontent.com/53708281/122308649-c6e4ae00-ceda-11eb-9228-c3102861e89e.png)
![Screen Shot 2021-06-16 at 6 42 28 PM](https://user-images.githubusercontent.com/53708281/122308663-cea45280-ceda-11eb-8123-00719581906e.png)
In both WebMessage and SMServer, my first attempt at creating a new chat with an image failed, but my second attempt succeeded. I filmed both attempts for SMServer, and I filmed only the second attempt for WebMessage.

https://user-images.githubusercontent.com/53708281/122308975-70c43a80-cedb-11eb-8da1-3db73fae5b68.mp4

https://user-images.githubusercontent.com/53708281/122308987-76218500-cedb-11eb-8595-75abf733ee51.mp4

I was unable to test this in MyMessage as the create new chat button does not currently work.

https://user-images.githubusercontent.com/53708281/122309019-82a5dd80-cedb-11eb-8059-2f457aa1a6ef.mp4

Any thoughts for why it doesn't work in BlueBubbles, and why it takes two tries in WebMessage and SMServer? @iandwelker @sgtaziz.

**Comment by iandwelker** [comment] 2021-06-16 23:51
It doesn't work on SMServer simply cause I haven't yet added support for creating a conversation and then immediately sending an attachment to it (which, in hindsight, is kind of stupid since I could easily add support for it, I just never did), so it creates the conversation but then doesn't send a message to it.

Since the conversation already exists when you send the second message, it allows you to send an image to it.

**Comment by zlshames** [comment] 2021-06-17 00:10
@CSab6482 when the message timeout happens in the logs, is the image still being sent in iMessage? Because I was dumb and set the image send timeout to 1 minute, when it should be much longer

**Comment by CSab6482** [comment] 2021-06-17 00:11
> @CSab6482 when the message timeout happens in the logs, is the image still being sent in iMessage? Because I was dumb and set the image send timeout to 1 minute, when it should be much longer

No, it never goes through, but maybe that 1 minute timeout is what causes this bug? I will test this with AirMessage and post my results.

**Comment by zlshames** [comment] 2021-06-17 01:35
i think the timeout is the issue cuz im pretty sure that after a certain amount of time the attachment gets deleted too

**Comment by tneotia** [comment] 2022-11-29 15:01
We are going to leave this as a limitation that isnt possible until private api chat creation

**Closed by tneotia** 2022-11-29 15:01 UTC
Labels: Bug, Bot Created, Difficulty: Medium
