### ISSUE TITLE
Requested resource not found at getClientConfig (google-services.json required even when not used)

### ISSUE THREAD

**Issue by a10kiloham** [BlueBubblesApp/bluebubbles-app#2517] opened 2023-07-11 07:56 UTC
I have bug find but discovered a fix. I have a Mac VM running Bluebubbles server (trying all three of the server 1.7.3, 1.74 stables and the 1.8.0 beta alternately.) 

On one laptop, I have an older Windows client something like 1.0.4 that works fine. I never bothered to update it.

However on my main Windows PC, I cannot connect at all. I've tried versions as far back as client v1.4 and in the server debug lobg it shows:

HI: [404] The requested resource was not found at getClientConfig
(then a stack trace to node_modules/koa-compose/index.js)
Then next line The requested resource was not found -> Google Services file not found.

I don't use Google Services at all.

***** SOLUTION ******
Even though I'm on iOS only and don't use Google Services as I have a direct URL to my server, uploading the google-services.json seems to immediately fix the problem. This is confusing as I can't see any need for it in my configuration not using Firebase.

**Comment by zlshames** [comment] 2023-07-11 11:48
Yeah the issue is I guess the client doesn't expect the 404 and causes the client to "crash" out of the setup process. You can probably remove it once the initial sync completes.

**Comment by tneotia** [comment] 2023-08-19 19:09
should be fixed in upcoming builds

**Closed by tneotia** 2023-08-19 19:09 UTC
