### ISSUE TITLE
iMessage reactions don't separate when multiple images are sent in one message

### ISSUE THREAD

**Issue by Andrew-M3373** [BlueBubblesApp/bluebubbles-app#2182] opened 2022-07-07 19:09 UTC
When multiple photos are received under the same message, all reactions are listed under the topmost image instead of whichever image is reacted to. The same issue occurs when reactions are received: if the third image was reacted to, it will always show on the first image since they are all part of the same message.

**Comment by tneotia** [comment] 2022-07-07 19:20
Duplicate of #542

**Closed** 2022-07-07 19:20 UTC
