### ISSUE TITLE
Bluebubbles fails to run on Asahi Linux

### ISSUE THREAD

**Issue by lacamar** [BlueBubblesApp/bluebubbles-app#2433] opened 2023-03-22 21:17 UTC
When attempting to run the Blueblubbles aarch64 flatpak on Asahi Linux (M1 Pro aarch64 hardware), it returns this error:

`bluebubbles: error while loading shared libraries: libpdfium.so: ELF load command address/offset not page-aligned`

This is likely due to the 16k pages that Asahi Linux uses

**Comment by jjoelj** [comment] 2023-03-25 03:14
https://github.com/AsahiLinux/docs/wiki/Broken-Software#:~:text=Fixed%20since%201.5.0-,pdfium,-https%3A//bugs.chromium

Looks like it's been fixed upstream. I'll see if I can upgrade the dependency.

**Comment by jjoelj** [comment] 2023-04-09 13:21
@lacamar A new version has been published to the flathub beta repo. Could you let me know if the issue is resolved? Thanks.

**Comment by lacamar** [comment] 2023-04-10 13:20
I can't seem to find the beta flathub package, is that publicly available?
I managed to manually update libpdfium for my install of the most recent public flathub package and I was able to run bluebubbles, though it was very slow. I would guess that's due to the GPU drivers not being fully functional yet.

**Comment by jjoelj** [comment] 2023-04-10 15:07
You should be able to install the beta after adding the beta repo.

```flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo```

**Comment by lacamar** [comment] 2023-04-12 17:10
I installed the beta from that repo but I'm getting the same error. It looks like it isn't pulling the latest version.

`$ flatpak info app.bluebubbles.BlueBubbles 

BlueBubbles - BlueBubbles client for Linux

          ID: app.bluebubbles.BlueBubbles
         Ref: app/app.bluebubbles.BlueBubbles/aarch64/beta
        Arch: aarch64
      Branch: beta
     Version: 1.11.100.0
     License: Apache-2.0
      Origin: flathub-beta
  Collection: org.flathub.Beta
Installation: user
   Installed: 56.2 MB
     Runtime: org.gnome.Platform/aarch64/43
         Sdk: org.gnome.Sdk/aarch64/43

      Commit: 031eb8cf8ff74a1d744a19eb53213d6457e5fb01cb0f4e3185603e5396f4f02e
      Parent: 6e7f4633378e96d62bb64e814b12a7727d3c2c0fbaa6f25b7ace63d21cc0a4db
     Subject: Update to 1.11.100.0 Beta (e3046959)
        Date: 2023-04-09 13:11:41 +0000
$ flatpak run app.bluebubbles.BlueBubbles  
bluebubbles: error while loading shared libraries: libpdfium.so: ELF load command address/offset not page-aligned`

**Comment by tneotia** [comment] 2023-04-12 18:07
That is the latest version, so seems like its still an issue

**Comment by jjoelj** [comment] 2023-04-12 18:19
Well pdfium appears to download the latest version every time I build according to its CMakeLists.txt, and according to the link I sent earlier, it should be fixed since chromium 108. The latest release is on chromium 114 now....

So I'm not sure what else I can try. How did you manually update the package for your install @lacamar ?

**Comment by lacamar** [comment] 2023-04-12 18:42
I downloaded and extracted "pdfium-linux-arm64.tgz" from this repo: https://github.com/bblanchon/pdfium-binaries/releases
After that I deleted the libpdfium.so file located at /var/lib/flatpak/app/app.bluebubbles.BlueBubbles/current/active/files/bluebubbles/lib/, then I copied libpdfium.so downloaded from the repo to that directory. 
After that bluebubbles just runs as usual via flatpak run app.bluebubbles.BlueBubbles.

**Comment by jjoelj** [comment] 2023-04-12 18:49
That's what the CMake *should* be doing. I can probably replicate what you did in the flatpak config. I'll let you know when I release another beta version to flathub in a bit

**Comment by jjoelj** [comment] 2023-04-12 20:19
@lacamar Just published 1.11.100.1 to flathub beta which downloads and places the libpdfium.so file like you did. Lmk if it works.

**Comment by lacamar** [comment] 2023-04-13 06:55
Just tested it, that worked. The flatpak just runs now.

**Closed** 2023-04-18 20:19 UTC
